version: '3'

services:
  api:
    build:
      context: ../
      dockerfile: docker/api-py-37.dockerfile
    env_file:
      - api.env
    ports:
      - "80:80"

  frontend:
    build:
      context: ../
      dockerfile: docker/frontend-py-37.dockerfile
    env_file:
      - frontend.env
    ports:
      - "8501:8501"
    depends_on:
      - api
