version: '3'
services:
  api:
    build:
      context: ../
      dockerfile: docker/api-py-37.dockerfile
      args:
        # add ip, port, at least
        MAX_WORKERS: "1"
    ports:
      - "80:80"
    volumes:
      - ./storage:/storage
  frontend:
    build:
      context: ../
      dockerfile: docker/streamlit-py-37.dockerfile
      args:
        API_ADDRESS_IP: "api"
        API_ADDRESS_PORT: "80"
        STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./storage:/storage
