version: '3'

services:
  api:
    build:
      context: ../
      dockerfile: docker/api-py-37.dockerfile
    env_file:
      - api.env
    ports:
      - "80:80"
    volumes:
      - ./storage:/storage

  streamlit:
    build:
      context: ../
      dockerfile: docker/streamlit-py-37.dockerfile
    env_file:
      - streamlit.env
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ./storage:/storage
